name: Build and Test GPU Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl wget

      - name: Install CUDA 12.6
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Set up environment for CUDA
        run: |
          export PATH=/usr/local/cuda-12.6/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
          export CUDACXX=/usr/local/cuda-12.6/bin/nvcc
          echo "PATH: $PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CUDACXX: $CUDACXX"

      - name: Verify CUDA installation
        run: |
          which nvcc
          nvcc --version
          ls -l /usr/local/cuda-12.6/bin/nvcc

      - name: Configure the project with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ./gpu_miner
