name: Build and Test GPU Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installation des dépendances nécessaires
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl wget gnupg

      # Ajout du repository NVIDIA pour CUDA 12.6
      - name: Add NVIDIA repository for CUDA 12.6
        run: |
          sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/7fa2af80.pub
          sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
          sudo apt-get update

      # Installation de CUDA 12.6
      - name: Install CUDA 12.6
        run: |
          sudo apt-get install -y cuda-12-6

      # Configuration des variables d'environnement pour CUDA 12.6
      - name: Set up environment for CUDA 12.6
        run: |
          echo "Setting up environment for CUDA 12.6"
          export PATH=/usr/local/cuda-12.6/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
          export CUDACXX=/usr/local/cuda-12.6/bin/nvcc
          echo "PATH: $PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CUDACXX: $CUDACXX"

      # Vérification de l'installation de CUDA 12.6
      - name: Verify CUDA 12.6 installation
        run: |
          which nvcc
          nvcc --version
          ls -l /usr/local/cuda-12.6/bin/nvcc

      # Configuration du projet avec CMake
      - name: Configure the project with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      # Compilation du projet
      - name: Build the project
        run: |
          cd build
          make

      # Test du projet (exécution du programme)
      - name: Run tests
        run: |
          cd build
          ./gpu_miner
