name: Build and Test GPU Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu (le runner par défaut de GitHub Actions)

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installation des dépendances nécessaires
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl wget

      # Installation de CUDA 12.6 sur Ubuntu (via NVIDIA apt repository)
      - name: Install CUDA 12.6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
          wget https://developer.download.nvidia.com/compute/cuda/12.6.0/local_installers/cuda_12.6.0_530.30.02_linux.run
          sudo sh cuda_12.6.0_530.30.02_linux.run --silent --toolkit

      # Configuration des variables d'environnement pour CUDA 12.6
      - name: Set up environment for CUDA 12.6
        run: |
          echo "Setting up environment for CUDA 12.6"
          export PATH=/usr/local/cuda-12.6/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
          export CUDACXX=/usr/local/cuda-12.6/bin/nvcc
          echo "PATH: $PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CUDACXX: $CUDACXX"

      # Vérification de l'installation de CUDA 12.6
      - name: Verify CUDA 12.6 installation
        run: |
          which nvcc
          nvcc --version
          ls -l /usr/local/cuda-12.6/bin/nvcc

      # Configuration du projet avec CMake
      - name: Configure the project with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      # Compilation du projet
      - name: Build the project
        run: |
          cd build
          make

      # Test du projet (exécution du programme)
      - name: Run tests
        run: |
          cd build
          ./gpu_miner
