name: Build and Test GPU Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise l'environnement Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl

      - name: Install CUDA 12.6
        run: |
          sudo apt-get update
          sudo apt-get install -y nvidia-cuda-toolkit

      - name: Set up CUDA paths
        run: |
          export CUDA_TOOLKIT_ROOT_DIR="/usr/local/cuda-12.6"
          export PATH=$CUDA_TOOLKIT_ROOT_DIR/bin:$PATH
          export LD_LIBRARY_PATH=$CUDA_TOOLKIT_ROOT_DIR/lib64:$LD_LIBRARY_PATH
          export CUDACXX=$CUDA_TOOLKIT_ROOT_DIR/bin/nvcc

      - name: Verify CUDA installation
        run: |
          nvcc --version
          which nvcc

      - name: Configure the project with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ./gpu_miner
